## Where the samples will be written
save_data: data/dstc7-ubuntu/run/

## Where the vocab(s) will be written
src_vocab: data/dstc7-ubuntu/run/vocab.src
tgt_vocab: data/dstc7-ubuntu/run/vocab.tgt

# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: data/dstc7-ubuntu/train.src.txt
        path_tgt: data/dstc7-ubuntu/train.tgt.txt
    valid:
        path_src: data/dstc7-ubuntu/dev.src.txt
        path_tgt: data/dstc7-ubuntu/dev.tgt.txt

# ----------------------------
# data: data/dstc7-ubuntu/run/

# Vocabulary files that were just created
src_vocab: data/dstc7-ubuntu/run/vocab.src
tgt_vocab: data/dstc7-ubuntu/run/vocab.tgt

save_model: data/dstc7-ubuntu/run/transformer_wordvocab
save_checkpoint_steps: 30
keep_checkpoint: 15
early_stopping: 14
early_stopping_criteria: ppl
seed: 3435
train_steps: 3000
valid_steps: 30
warmup_steps: 30
report_every: 10

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 2048
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 4
gpu_ranks:
- 0
- 1
- 2
- 3